server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  could:
    gateway:
      routes:
        - id: SONG-SERVICE
          uri: lb://SONG-SERVICE
          predicates:
            - Path=/songs/**
        - id: SINGER-SERVICE
          uri: lb://SINGER-SERVICE
          predicates:
            - Path=/singers/**

eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true;
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost



